ssl = yes
ssl_cert = </etc/dovecot/certs/mail.crt
ssl_key = </etc/dovecot/private/mail.key
ssl_min_protocol = TLSv1.2
ssl_cipher_list = ALL:!kRSA:!SRP:!kDHd:!DSS:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!PSK:!RC4:!ADH:!LOW@STRENGTH

